/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.ApiConnector;
import controller.Client;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lab.QCPlatform;
import org.json.simple.JSONArray;
import user.UserReg;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import user.UserManager;

/**
 *
 * @author Tharusha
 */
public class Login extends javax.swing.JFrame {

    public String username;
    
    /**
     * Creates new form Login
     */
    public Login() {

        lookandfeels();
        initComponents();
        lookandfeels();
        ImageIcon icon = new ImageIcon("Image/icon2.png");
        setIconImage(icon.getImage());
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon1 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblgreet = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        btnlog = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        Label_Verification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Window");
        getContentPane().setLayout(null);

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/plus.png"))); // NOI18N
        getContentPane().add(lblIcon1);
        lblIcon1.setBounds(190, 160, 24, 24);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/user_male_Edit.png"))); // NOI18N
        getContentPane().add(lblIcon);
        lblIcon.setBounds(83, 17, 165, 165);

        lblgreet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblgreet.setText("Hi User");
        lblgreet.setAutoscrolls(true);
        lblgreet.setName("lblUName"); // NOI18N
        lblgreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblgreetMouseClicked(evt);
            }
        });
        getContentPane().add(lblgreet);
        lblgreet.setBounds(126, 200, 76, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Powerd By");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(6, 385, 68, 14);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Blimp_50x.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 405, 58, 15);

        psw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        psw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psw.setToolTipText("Password");
        psw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pswMouseEntered(evt);
            }
        });
        getContentPane().add(psw);
        psw.setBounds(40, 313, 256, 21);

        txtUserName.setText("User Name");
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserNameMouseEntered(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(40, 272, 256, 23);

        btnlog.setText("Login");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(108, 352, 123, 25);

        btnsignup.setText("Signup");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup);
        btnsignup.setBounds(254, 8, 79, 31);

        Label_Verification.setFont(new java.awt.Font("Manjari Regular", 0, 8)); // NOI18N
        Label_Verification.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(Label_Verification);
        Label_Verification.setBounds(40, 249, 256, 17);

        setSize(new java.awt.Dimension(346, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed

        username = txtUserName.getText();
      JSONObject jsonObject = new JSONObject(); //for Send UserName & Password to BackEnd (Verify)
      JSONObject jsonObjectLog = new JSONObject(); // for Store Log Count
      JSONObject jsonObjectUpdate =  new JSONObject(); // for Store updated data
      
      Client client = new Client(); 
      JSONParser parser = new JSONParser();
      JSONArray jsonArray = null;
      int count=0;
      
       if((txtUserName.getText()==null)||(psw.getText()==null))
      {
          JOptionPane.showMessageDialog(null,"Please Enter valid Username and Password");
      }
      else
      {

          try {
               jsonObject.put("username",txtUserName.getText());
               jsonObject.put("password",client.encrypt(psw.getText()));
          
          } catch (UnsupportedEncodingException ex) {
             Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null, ex);

          }
          ApiConnector apiConnector = new ApiConnector();
        String getLogin =  apiConnector.post("http://localhost:8080/api/usrmgtservice/login",jsonObject);
          
          
          String get = apiConnector.get("http://localhost:8080/api/usrmgtservice/logcount");
          try{
              jsonArray = (JSONArray) parser.parse(get);
              jsonObjectLog=(JSONObject) jsonArray.get(0);
              count= Integer.parseInt(jsonObjectLog.get("logcount").toString());
                            
          }catch(ParseException ex)
          {
               Logger.getLogger(UserManager.class.getName()).log(Level.SEVERE, null, ex);
          }
          
          if(getLogin.equals("Login Success\r")){
            if(txtUserName.getText().equals("admin")&& count == 0)
            {
                jsonObjectUpdate.put("username","admin");
                jsonObjectUpdate.put("logcount","1");
                client.sendData("http://localhost:8080/api/usrmgtservice/logupdate", jsonObjectUpdate);
                    Password_Reset pr = new Password_Reset();
                    pr.setVisible(true);
                    this.dispose();
            }   
            else if(txtUserName.getText().equals("admin")&& count == 1)
            {
                    VergerMain vergermain = new VergerMain("admin");
                    vergermain.setVisible(true);
                    this.dispose();
            }
            
            else{
                String name = txtUserName.getText();
                VergerMain vm = new VergerMain(name);
                vm.setVisible(true);
                this.dispose();
            }
          }else{
              Label_Verification.setText(getLogin);
              txtUserName.setText("");
              psw.setText("");
          }
          
      }
       
    }//GEN-LAST:event_btnlogActionPerformed

    private void txtUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseEntered
        if (txtUserName.getText().equals("User Name")) {
            txtUserName.setText("");
        }

    }//GEN-LAST:event_txtUserNameMouseEntered

    private void pswMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswMouseEntered
        if (!txtUserName.getText().equals("User Name")) {
            lblgreet.setText("Hi " + txtUserName.getText());
        }
    }//GEN-LAST:event_pswMouseEntered

    private void lblgreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgreetMouseClicked
        
    }//GEN-LAST:event_lblgreetMouseClicked

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        
        UserReg userRegistration = new UserReg();
        userRegistration.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnsignupActionPerformed

    static public void lookandfeels() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }

                javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        lookandfeels();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lookandfeels();
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Verification;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblgreet;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
